### ISSUE TITLE
[WINDOWS]Create a Batchfile to run the makefile commands

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#10]
For now, Users that want to use TYRBO-on-terminal need to open a terminal initially to run the makefiles using commands.
```
 mingw32-make -f mktyrbo.mk
```
This is not very convenient. Create a batchfiile for windows that will run the commands on its own.

**Comment by bit8mayank** [comment]
hey can i work on this issue ?

**Comment by sruthiroyal28** [comment]
CAN I WORK ON THIS??

**Comment by bit8mayank** [comment]
@Typeaway14  can i work on this issue ?

**Comment by Typeaway14** [comment]
Hi @bit8mayank You may work on this now, you have been assigned!

@sruthiroyal28 pls dont shout at me T_T (also wait for bit8mayank)

**Comment by Typeaway14** [comment]
This issue has been closed by #18
