### ISSUE TITLE
[LINUX]Add a feature that detects CAPS LOCK during typing

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#11]
A feature to detect and inform the user that CAPS LOCK IS ON is implemented for the Windows OS. 

When CAPS LOCK is on:
![image](https://user-images.githubusercontent.com/92392779/196669139-7ed53e45-e080-4832-af41-b508f80405da.png)
When CAPS LOCK is turned off:
![image](https://user-images.githubusercontent.com/92392779/196669270-11aef1c0-37af-4ccb-b386-0711efe98c9e.png)

Implement a similar feature for Linux, making sure it looks exactly like how it does on Windows.

**Comment by Ganther3301** [comment]
i would like to work on this

**Comment by Typeaway14** [comment]
@Ganther3301 Go for it Ganther, You have been assigned! You have 1 hour to work on this. Anybody else wishing to be assigned, drop a message and wait in line

**Comment by procub3r** [comment]
@Typeaway14 I'd like to give this a go :grin:

**Comment by Typeaway14** [comment]
Ill be reassigning this issue to @procub3r ! Go ahead !

**Comment by Typeaway14** [comment]
This issue has been solved!
