### ISSUE TITLE
[OPEN ACCESS]Treasure Hunt?! 🤨

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#12]
There is a secret feature, built into the code but is not being used in the code. 
Find this code for some serious points 😎

Note: Try answering some Trivia (ask maintainer for Trivia questions!) for the maintainer to get some hints ;)

**Comment by TejasB02** [comment]
@Typeaway14 can I have this cuh? Love you bro I play monkeytype everyday and I have to thank my fate that I found your rep

**Comment by Aditikhasnis** [comment]
can i plz work on this !plzz

**Comment by Aditikhasnis** [comment]
can you plzz also tell the trivia questions

**Comment by Suhas-Kumararaja** [comment]
Can there be multiple people assigned to this? if yes, can i be assigned it too?

**Comment by Typeaway14** [comment]
@An-4lchemist I will allow that for this repo, thanks!

But I'll have to give it to 2 people ie @TejasB02 and @Aditikhasnis . Go ahead you two! You have 30 minutes for it :)

**Comment by Keshav1105** [comment]
Can i get in

**Comment by ad1tya24** [comment]
I would like to join

**Comment by surajkadapa** [comment]
I would like to be assigned to this

**Comment by Vaarun-C** [comment]
Please assign me to this :)

**Comment by BalajiRock** [comment]
i would like work on this :)

**Comment by Typeaway14** [comment]
THIS ISSUE IS NOW CLOSED! THE BOUNTY HAS BEEN EARNED!!
