### ISSUE TITLE
Document the BEAST!

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#13]
This one is killer, but so worth it!
`type_content.c` has a lot of poorly names variables, and has no documentation. Document all the code, and clean up the variables with meaningful names to score big points!

**Comment by TejasB02** [comment]
@Typeaway14  Can I have this issue

**Comment by Typeaway14** [comment]
Hey Tejas, it's open access season! You can make PRs without being assigned for the first hour

**Comment by TejasB02** [comment]
@Typeaway14 Can I have this issue pls?

**Comment by Geeker357** [comment]
Can I work on this, please? There is a problem with my python compiler and I need to work on C only. Pleaseee give it to me

**Comment by Typeaway14** [comment]
Hi @TejasB02 you've been assigned! You have 45 minutes until after the freeze time has closed to submit a PR. You can ask for extension if you have substantial work done !

**Comment by PavvanPradeep** [comment]
can i work on this

**Comment by Typeaway14** [comment]
@TejasB02 You have 45 minutes to submit a PR. Let's GO!

**Comment by TejasB02** [comment]
Do not consider the above PR I am submitting again

**Comment by Typeaway14** [comment]
Yes, I shall reject that one then! Send over the new PR :)

**Comment by Typeaway14** [comment]
THIS ISSUE IS FROZEN. CONSIDER IT CLOSED!!

**Comment by Typeaway14** [comment]
This issue is now closed! #15
