### ISSUE TITLE
Add make clean rule to remove *.o and target files

### ISSUE THREAD

**Issue by procub3r** [Typeaway14/TYRBO-on-terminal#16]
With how things are right now, we have to manually remove all the intermediate and target files before contributing.  
**Proposal**: create a make "clean" rule to do this for us automatically. This should make the dev workflow just a tad nicer :D

**Comment by procub3r** [comment]
@Typeaway14 ping pong (forgot to ping yet again :exit:)

**Comment by Typeaway14** [comment]
@procub3r Wonderful Idea! You have the green. Make it happen and I'll assign points to you :)

**Comment by Typeaway14** [comment]
This issue has been solved!
