### ISSUE TITLE
[LINUX]Figure out a way to clear Input Stream

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#4]
The current implementation for preventing overflow of the inputs into the basketball game mode(while throwing random word after a successful streak) is to disable the keyboard using a shell script that is triggered at a moment in the code, and then re-enabled when needed.
However, this has some issues:

- Currently the shell script is hard coded to work only on my(Typeaway14) laptop. This was done for me to test whether this is a viable approach or not. THIS WILL NOT WORK ON EVERY DEVICE
- It is risky to have TYRBO disable the keyboard as in case the code fails to enable the keyboard, it will be a very annoying experience for the user
- This required executable permission to be granted (chmod+x). 

A better solution for this, which works on windows, is to clear the input stream at the required point in code. Figure out how to do this in Linux!

**Comment by n1haldev** [comment]
Can I get this assigned please?

**Comment by Typeaway14** [comment]
Go ahead, @n1haldev!
