### ISSUE TITLE
Add a feature that allows user to change the color of the animations

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#6]
TYRBO-on-terminal displays some art in multiple stages of the program. The default color is green. Add a feature to allow the user to change color by passing certain flags while giving the command to run the program!

Ensure this color the user sets is remembered and needs to be set only once. What colors to add is upto your discretion, make sure you add the instruction to change color in  `help()` ! Add your favourites :)

**BONUS POINTS:** Add funny creative names for the colors in the help menu (trigger on calling tyrbo with empty flags). 
examples:
 Blue -> Bootiful Blue.
 Red -> Zubaan Kesari (uk I had to @_@)

**Comment by Aditikhasnis** [comment]
hey! can i work on this

**Comment by sruthiroyal28** [comment]
i would like to work on this . can u assign it to me??

**Comment by Typeaway14** [comment]
Go ahead @sruthiroyal28 !

**Comment by n1haldev** [comment]
Can I be assigned to this?

**Comment by Typeaway14** [comment]
@n1haldev Go ahead!

**Comment by Typeaway14** [comment]
This issue has been closed by the latest commit :)

**Comment by Typeaway14** [comment]
This issue has been closed by the latest commit :)
