### ISSUE TITLE
[LINUX] init command issues

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#7]
Running `tyrbo init` on windows works perfectly but causes the program to launch with a random game mode on Linux. The expected behavior is to show a message saying the process is complete and exit the program. Find a fix for this!

**Comment by KunalMaverick** [comment]
Can i be assigned to this?

**Comment by n1haldev** [comment]
Can I be assigned to this?

**Comment by Typeaway14** [comment]
Go ahead @n1haldev!
