### ISSUE TITLE
Document the Baby Dragons

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#8]
Try to figure out the code and add helpful documentation for the various files! 
The better the documentation, the more the points!
 - `type_content.h`: 5 Bounty Points
 - `client.c`: 5 Bounty Points
 - `tc.c`: 5 Bounty Points
 - `tc.h`: 5 Bounty Points

**Comment by Geeker357** [comment]
Can I work on this, please? There is a problem with my python compiler and I need to work on C only. Pleaseee give it to me

**Comment by Typeaway14** [comment]
@Geeker357 You may work on this! You have been assigned!

**Comment by TejasB02** [comment]
Can I work on this bro? Also come to Seminar Hall 1 for treasure hunt

**Comment by Typeaway14** [comment]
Ill be reassigning this to @TejasB02!

**Comment by Geeker357** [comment]
dude give me 15 more min , please

**Comment by Geeker357** [comment]
I got started already. Can I please submit it

**Comment by Typeaway14** [comment]
Sorry you didnt give us an update :/
let's wait for a while

**Comment by varuni7** [comment]
Can I work on this?

**Comment by Typeaway14** [comment]
Go ahead Varuni! @varuni7

**Comment by siddarthpai** [comment]
hey can i work on this

**Comment by Typeaway14** [comment]
@siddarthpai go for it !

**Comment by abhiraj2** [comment]
can I work on this?

**Comment by Typeaway14** [comment]
Open access, go ahead!
