### ISSUE TITLE
[LINUX] Create a shell script to run the make file

### ISSUE THREAD

**Issue by Typeaway14** [Typeaway14/TYRBO-on-terminal#9]
For now, Users that want to use TYRBO-on-terminal need to open a terminal initially to run the makefiles using commands.
```
make -f mktyrbo.mk
```
 This is not very convenient. Create a shell script for Linux that will run the commands on its own.

**Comment by procub3r** [comment]
Could you please assign this issue to me?
PRN: PES2202200415
Name: Sriprad Potukuchi

**Comment by Typeaway14** [comment]
Hey @procub3r it's open access!
Go ahead and make a PR!

**Comment by Typeaway14** [comment]
Thanks @procub3r! I have merged #14
